name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache engine repository
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-engine-repo-${{ github.sha }} #???
          path: ~/engine-repo
          restore-keys: |
            ${{ runner.os }}-engine-repo-

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: |
          if[ ! -d "~/engine-repo" ]; then
            git clone https://github.com/Noxagonal/Bitcrafte-Engine.git ~/engine-repo
          fi

      - run: sudo apt update && sudo apt install -y doxygen
      - run: pip install mkdocs-material mkdoxy
      - run: mkdocs gh-deploy --force
